### ISSUE TITLE
Eliminar Console.log

### ISSUE THREAD

**Issue by Nidev-lab** [gerogarzon/e-menu#3]
Buenas! como estan? encontré algunos console.log que deberian eliminar.

![image](https://user-images.githubusercontent.com/53904695/192663571-f4d61a0e-d3a3-44f2-9488-8aaa217b365e.png)

Cualquier cosita podes contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode

**Comment by gerogarzon** [comment]
Hola Nico, ¿cómo estás?

Estoy corrigiendo ahora mismo aprovechando que estás mirando el proyecto!

**Comment by Nidev-lab** [comment]
Buenas! pude comprobar que está solucionado lo del error en el logueo, pero lo de los comentarios y console.log, tanto en Font como en back siguen apareciendo... 
![image](https://user-images.githubusercontent.com/53904695/193715752-c9cc622c-26d4-45b4-9a1b-9afd7500ac6f.png)

Cualquier cosita podes contactarme a [nicogonzalez2008@gmail.com](mailto:nicogonzalez2008@gmail.com) o por el slack de RollingCode
